/**
 * EL OBJETIVO DE ESTA CLASE ES COMENTAR QUE SE DARAN LOS
 * RECURSOS NECESARIOS EN CUANTO SCSS QUE PUES USA UNA
 * SINTAXIS TOTALMENTE DISTINTA-QUEDA PENDIENTE APRENDERLO
 * Y EXPLORAR SUS CARACTERISTICAS NUEVAS-
 */