/**
 * EL OBJETIVO DE ESTA CLASE ES ACERCARNOS UN POCO MAS
 * A LA NAVEGACION QUE QUEREMOS A TRAVES DE LA ACCION EN 
 * PARA INGRESAR EN CADA UNA DE LAS LECCIONES PARA LO CUAL
 * DE 'REACT ROUTER' NOS VALDREMOS DE DOS PROPIEDADES 'LINK'
 * E 'HISTORY' Y 'HOF' -HIGH ORDER COMPONENTS QUE SE ENCARGA 
 * DE TOMAR OTROS COMPONENTES COMO ARGUMENTO Y LO TRANSFORMA
 * EN OTRO COMPONENTE Y RETORNA EL COMPONENTE RESULTANTE- 
 */